### PR TITLE
Use Closure binding instead of PropertyAccessor when manipulating objects

### LINKED ISSUE #68: Get and set files property through reflection
If class has file field but doesn't has setter for it, for example file is set in constructor, then `NoSuchPropertyException` is thrown [down here](https://github.com/fsi-open/doctrine-extensions/blob/master/lib/FSi/DoctrineExtensions/Uploadable/UploadableListener.php#L365)

It should be done as doctrine do this - through reflection.

revert https://github.com/fsi-open/doctrine-extensions/pull/8

Moreover getters should also change. Current implementation with PropertyAccessor block developers from using php7 return types declaration.

### PR DESCRIPTION
**Pull request by szymach**
Resolves #68

### CODE REVIEW

**Comment by szymach** [comment]
@fsi-open

**Comment by chives** [comment]
Two things to consider:
- we should not create `ReflectionClass` / `ReflectionProperty` on every single property access; maybe we can use `TranslatableMetadata` to read/write translatable properties and cache `ReflectionProperty` objects for every translatable property inside of it (doctrine ORM uses similar approach in `ClassMetadataInfo::(get|set)FieldValue()`)
- alternative solution for reflection is closure binding - https://ocramius.github.io/blog/accessing-private-php-class-members-without-reflection/

**Comment by szymach** [comment]
@fsi-open comments?

File: lib/FSi/DoctrineExtensions/PropertyManipulator.php [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+     * @param string $propertyPath
+     * @param mixed $value
+     */
+    public function setPropertyValue($object, $propertyPath, $value)
+    {
+        $this->assertIsObject($object);
+
+        Closure::bind(function () use ($propertyPath, $value) {
+            return $this->$propertyPath = $value;
+        }, $object, $this->getSourceObjectForProperty($object, $propertyPath))->__invoke();
```
Comment (JarekW) [inline lib/FSi/DoctrineExtensions/PropertyManipulator.php]: w sumie to samo, ale mozna czy nie ładniej wyglada:

```php
$this->setClosure = function($propertyName, $value) {
    $this->$propertyName = $value;
}

$this->setClosure
    ->bindTo($object, $this->getSourceObjectForProperty($object, $propertyPath))
    ->__invoke($propertyPath, $value);

// =========================

$this->getClosure = function($propertyName) {
    return $this->$propertyName;
}
return $this->getClosure
    ->bindTo($object, $this->getSourceObjectForProperty($object, $propertyPath))
    ->__invoke($propertyPath)
```

**Comment by szymach** [comment]
@fsi-open

File: lib/FSi/DoctrineExtensions/PropertyManipulator.php [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+    {
+        $this->assertIsObject($object);
+
+        $oid = spl_object_hash($object);
+        if (!isset($this->bindings[$oid][$name])) {
+            $closure = Closure::bind(function () use ($name) {
+                return $this->$name;
+            }, $object, $this->getSourceObjectForProperty($object, $name));
+
+            $this->bindings[$oid][$name] = $closure;
```
Comment (chives) [inline lib/FSi/DoctrineExtensions/PropertyManipulator.php]: I'm not sure if cache'ing closures per specific object per specific property speeds up anything. It would make sense to cache "getter" for specific class and property but that is against closures' nature. I would remove the cache for now. It will be 2x faster than reflection anyway (without reflection cache).

File: lib/FSi/DoctrineExtensions/PropertyManipulator.php [hunk 3]
```diff
@@ -0,0 +1,188 @@
...
+     * @var array
+     */
+    private $savedValues = [];
+
+    /**
+     * @param object $object
+     * @param string $name
+     * @param mixed $value
+     */
+    public function setAndSaveValue($object, $name, $value)
```
Comment (chives) [inline lib/FSi/DoctrineExtensions/PropertyManipulator.php]: please rename `$name` to `$property` in all methods

File: tests/FSi/DoctrineExtensions/Tests/Translatable/ListenerTest.php [hunk 4]
```diff
@@ -180,7 +206,7 @@ public function testInsertWithTwoTranslationsClearAndLoad()
         $article = $this->_em->find(self::ARTICLE, $article->getId());
 
         $this->assertEquals(
-            3,
+            2,
```
Comment (chives) [inline tests/FSi/DoctrineExtensions/Tests/Translatable/ListenerTest.php]: This is probably wrong because translatable collection would not be loaded. There are missing tests for persisting/loading translatable collection. `PropertyAccessor` ensured loading such a collection by calling its getter. Now we have to trigger lazy load for collections before setting/getting them

**Comment by szymach** [comment]
@fsi-open

File: lib/FSi/DoctrineExtensions/Translatable/TranslationHelper.php [hunk 5]
```diff
@@ -182,43 +176,27 @@ public function getObjectLocale(ClassTranslationContext $context, $object)
...
-                && $propertyAccessor->getValue($target, $targetField) === null
-            ) {
-                $reflection = new \ReflectionClass($target);
-                $property = $reflection->getProperty($targetField);
-                $property->setAccessible(true);
-                $property->setValue($target, new ArrayCollection());
-                $property->setAccessible(false);
+            $sourceProperty = $this->propertyManipulator->getPropertyValue($source, $sourceField);
+            if ($sourceProperty instanceof PersistentCollection) {
+                $sourceProperty->initialize();
```
Comment (chives) [inline lib/FSi/DoctrineExtensions/Translatable/TranslationHelper.php]: There should be a bunch of tests that verify if collection created/modified throught translatable/translation object is readable from translation/translatable object after flushing and clearing entity manager. These tests will show if this initialization is necessary.

**Comment by szymach** [comment]
@fsi-open check the new method of handling collections

**Comment by szymach** [comment]
@fsi-open

**Comment by szymach** [comment]
@fsi-open
